/* Generated by flagwire-typegen. Do not edit manually. */
import type {} from "@flagwire/sdk-js";
import type {} from "@flagwire/sdk-node";

export type FlagKey = "example.checkout";

export interface FlagwireGeneratedFlags {
  readonly "example.checkout": boolean;
}

declare module "@flagwire/sdk-js" {
  interface FlagwireFlags {
    readonly "example.checkout": boolean;
  }
}

declare module "@flagwire/sdk-node" {
  interface FlagwireFlags {
    readonly "example.checkout": boolean;
  }
}

export {};
