/* Generated by flagwire-typegen. Do not edit manually. */
import type {} from "@flagwire/sdk-js";
import type {} from "@flagwire/sdk-node";

declare module "@flagwire/sdk-node" {
  interface FlagwireFlags {
    readonly "example.checkout": boolean;
  }
}
export {};
