#!/usr/bin/env node

import { realpathSync } from "node:fs";
import { mkdir, rename, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { pathToFileURL } from "node:url";

type JsonValue = null | boolean | number | string | JsonValue[] | { [key: string]: JsonValue };

export interface TypegenManifest {
  flags: Array<{
    key: string;
    type: "boolean" | "json" | "string";
    variants: Array<{ key: string; value: JsonValue }>;
  }>;
  projectId: string;
}

function literal(value: JsonValue): string {
  return JSON.stringify(value);
}

function valueType(flag: TypegenManifest["flags"][number]): string {
  if (flag.type === "boolean") return "boolean";
  const values = flag.variants
    .map((variant) => variant.value)
    .filter((value) => flag.type === "json" || typeof value === "string")
    .map(literal);
  return [...new Set(values)].join(" | ") || "never";
}

function properties(manifest: TypegenManifest): string {
  return manifest.flags
    .map((flag) => `    readonly ${JSON.stringify(flag.key)}: ${valueType(flag)};`)
    .join("\n");
}

export function generateTypes(manifest: TypegenManifest): string {
  const keys = manifest.flags.map((flag) => JSON.stringify(flag.key)).join(" | ") || "never";
  const body = properties(manifest);
  return `/* Generated by flagwire-typegen. Do not edit manually. */
import type {} from "@flagwire/sdk-js";
import type {} from "@flagwire/sdk-node";

export type FlagKey = ${keys};

export interface FlagwireGeneratedFlags {
${body}
}

declare module "@flagwire/sdk-js" {
  interface FlagwireFlags {
${body}
  }
}

declare module "@flagwire/sdk-node" {
  interface FlagwireFlags {
${body}
  }
}

export {};
`;
}

function parseArguments(argv: string[]) {
  const values = new Map<string, string>();
  for (let index = 0; index < argv.length; index += 1) {
    const argument = argv[index]!;
    if (argument === "--help" || argument === "-h") return { help: true } as const;
    if (!argument.startsWith("--")) throw new Error(`Unknown argument: ${argument}`);
    const equals = argument.indexOf("=");
    const name = argument.slice(2, equals === -1 ? undefined : equals);
    const value = equals === -1 ? argv[++index] : argument.slice(equals + 1);
    if (!value || value.startsWith("--")) throw new Error(`Missing value for --${name}`);
    if (!["base-url", "key", "out", "project"].includes(name)) {
      throw new Error(`Unknown option: --${name}`);
    }
    values.set(name, value);
  }
  return { help: false, values } as const;
}

function validManifest(input: unknown): input is TypegenManifest {
  if (!input || typeof input !== "object") return false;
  const value = input as Partial<TypegenManifest>;
  return (
    typeof value.projectId === "string" &&
    Array.isArray(value.flags) &&
    value.flags.every(
      (flag) =>
        flag !== null &&
        typeof flag === "object" &&
        typeof flag.key === "string" &&
        (flag.type === "boolean" || flag.type === "string" || flag.type === "json") &&
        Array.isArray(flag.variants) &&
        flag.variants.every(
          (variant) =>
            variant !== null &&
            typeof variant === "object" &&
            typeof variant.key === "string" &&
            "value" in variant,
        ),
    )
  );
}

export async function run(argv = process.argv.slice(2)): Promise<void> {
  const parsed = parseArguments(argv);
  if (parsed.help) {
    process.stdout.write(
      "Usage: flagwire-typegen --key sk_live_... --out src/flags.gen.ts [--project project_id] [--base-url https://api.flagwire.dev]\n",
    );
    return;
  }

  const key = parsed.values.get("key") ?? process.env.FLAGWIRE_SERVER_KEY;
  const output = parsed.values.get("out");
  if (!key || !/^sk_live_[A-Za-z0-9_-]{43}$/.test(key)) {
    throw new Error("Provide a valid server key with --key or FLAGWIRE_SERVER_KEY");
  }
  if (!output) throw new Error("Provide an output path with --out");

  const baseUrl = new URL(parsed.values.get("base-url") ?? "https://api.flagwire.dev");
  if (baseUrl.protocol !== "https:" && baseUrl.protocol !== "http:") {
    throw new Error("--base-url must use http or https");
  }
  if (baseUrl.username || baseUrl.password)
    throw new Error("--base-url cannot contain credentials");
  const project = parsed.values.get("project");
  const route = project ? `/v1/typegen/${encodeURIComponent(project)}` : "/v1/typegen";
  const response = await fetch(new URL(route, baseUrl), {
    headers: { Authorization: `Bearer ${key}` },
    signal: AbortSignal.timeout(15_000),
  });
  if (!response.ok) throw new Error(`FlagWire type generation failed with HTTP ${response.status}`);
  const declaredLength = Number(response.headers.get("Content-Length"));
  if (Number.isFinite(declaredLength) && declaredLength > 1_048_576) {
    throw new Error("FlagWire type manifest exceeded 1MB");
  }
  const text = await response.text();
  if (text.length > 1_048_576) throw new Error("FlagWire type manifest exceeded 1MB");
  let input: unknown;
  try {
    input = JSON.parse(text);
  } catch {
    throw new Error("FlagWire returned an invalid type manifest");
  }
  if (!validManifest(input)) throw new Error("FlagWire returned an invalid type manifest");

  const target = resolve(output);
  const temporary = `${target}.${process.pid}.tmp`;
  await mkdir(dirname(target), { recursive: true });
  await writeFile(temporary, generateTypes(input), { encoding: "utf8", mode: 0o644 });
  await rename(temporary, target);
  process.stdout.write(`Generated ${input.flags.length} FlagWire flag types in ${target}\n`);
}

const entry = process.argv[1] ? pathToFileURL(realpathSync(resolve(process.argv[1]))).href : "";
if (import.meta.url === entry) {
  void run().catch((error: unknown) => {
    process.stderr.write(`${error instanceof Error ? error.message : "Type generation failed"}\n`);
    process.exitCode = 1;
  });
}
